### ISSUE TITLE
[Feat] Issue 예시

### ISSUE THREAD

**Issue by kpk0616** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#1]
## 🛠 Issue

이슈 생성 방법입니다.
1. 타이틀에는 `[이슈태그] 이슈 내용` 을 적어줍니다 !
2. 우측에 있는 `Assignees`를 본인으로 설정합니닷 !
3. `이슈태그`, `본인 이름` 라벨을 달아줍니다 ! 

## 📝 To-do

- [ ] 여기에는 to-do를 적어주면 됩니다 ~!

아자아자 MC2 파이팅 !! 🔥

**Comment by DhKimy** [comment]
새 이슈 템플릿 설정으로 이슈를 닫습니다.
