### ISSUE TITLE
[Hotfix] 1인기능 및 2인 기능 View이동 오류

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#98]
## 🛠 Issue

1인 기능 관련된 뷰를 추가하면서 1인기능과 2인기능 모두 View를 이동할때 자동으로 뒤로가게 되는 오류가 발생합니다. 

## 📝 To-do

- [ ] app flow 수정
- [ ] navigation오류 수정

**Comment by DhKimy** [comment]
기획 변경, 앱 구조 변경으로 인해 이슈를 닫습니다.
